-- Up Migration

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mower_id TEXT,
  event_type TEXT NOT NULL,
  event_timestamp TIMESTAMPTZ,
  received_at TIMESTAMPTZ NOT NULL,
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  message_code INTEGER,
  message_severity TEXT,
  payload JSONB NOT NULL
);

CREATE INDEX idx_events_mower_timestamp
  ON events (mower_id, event_timestamp);

CREATE INDEX idx_events_type_timestamp
  ON events (event_type, event_timestamp);

CREATE UNIQUE INDEX idx_events_unique
  ON events (
    COALESCE(mower_id, ''),
    event_type,
    COALESCE(event_timestamp, '-infinity'::TIMESTAMPTZ),
    MD5(payload::TEXT)
  );

CREATE TABLE positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mower_id TEXT,
  session_id BIGINT,
  activity TEXT,
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  timestamp TIMESTAMPTZ,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE
);

CREATE INDEX idx_positions_mower_timestamp
  ON positions (mower_id, timestamp);

CREATE UNIQUE INDEX idx_positions_unique
  ON positions (
    COALESCE(mower_id, ''),
    COALESCE(timestamp, '-infinity'::TIMESTAMPTZ),
    COALESCE(lat, 'NaN'::DOUBLE PRECISION),
    COALESCE(lon, 'NaN'::DOUBLE PRECISION)
  );

CREATE UNIQUE INDEX idx_positions_event_unique
  ON positions (event_id)
  WHERE event_id IS NOT NULL;

-- Down Migration

DROP TABLE positions;
DROP TABLE events;
